close all hidden;
clear all;

Matrixbinning=0.02;
Msize=2*1;

binning = 0.5e-12;
LY = 4577; % Light Yield 
CY = 30; % Cerenkov yield
a = LY / CY * (1 / (1 + LY/CY)); % normalization light yield
b = 1 / (1 + LY / CY); % normalization cerenkov yield
s = 66e-12; % sigma trans
t_d = 30.3e-9; % decay time
t_r = 70e-12; % rise time
l = 10.0e-12; % cerenkov sigma
theta = 1000e-12; % gamma time, parameter CR LB
tsk = 2e-9; % media trans

cer_min = theta; % cer min
cer_mean = theta + 2*l;

norm_s = 1.0 / (t_d-t_r); % normalization shao
norm_irf = 1. / (s * sqrt(pi/2) * ( 1 + erf(tsk / s / sqrt(2))));% normalization gaussian
norm_c =  1. / (l * sqrt(pi/2) * (1 + erf((cer_mean - cer_min)/ sqrt(2) / l))); % cerenkov normalization 
norm_irf_easy = 1. / (s * sqrt(pi() / 2) * (1 + erf((tsk + cer_mean) / sqrt(2) / s)));

N = CY + LY;
n = 1;


CF=@(t) (b * norm_irf * sqrt(pi / 2) * s *... 
        (erf((t-tsk-cer_mean)/(s*sqrt(2))) + erf((tsk+cer_mean)/(s*sqrt(2)))))+... 
          a * norm_irf * s * sqrt(pi/2)*...
           ((erf((t-theta-tsk)/s/sqrt(2))+erf(tsk/s/sqrt(2)))+... 
         (t_r/(t_d-t_r)*exp((-2*t*t_r+2*t_r*theta+2*t_r*tsk+s*s)/2/t_r/t_r).*...
           (erf((t-theta-tsk-s*s/t_r)/(s*sqrt(2)))+erf((tsk+s*s/t_r)/s/sqrt(2))))-...
         (t_d/(t_d-t_r)*exp((-2*t*t_d+2*t_d*theta+2*t_d*tsk+s*s)/2/t_d/t_d).*...
          (erf((t-theta-tsk-s*s/t_d)/s/sqrt(2))+erf((tsk+s*s/t_d)/s/sqrt(2)))));

FS=@(t) nchoosek(N, n)*n*...
        ((b * norm_irf * sqrt(pi / 2) * s *... 
        (erf((t-tsk-cer_mean)/(s*sqrt(2))) + erf((tsk+cer_mean)/(s*sqrt(2)))) + ...
          a*norm_irf*s*sqrt(pi/2)*...
         ((erf((t-theta-tsk)/s/sqrt(2))+erf(tsk/s/sqrt(2)))+...
          (t_r/(t_d-t_r)*exp((-2*t*t_r+2*t_r*theta+2*t_r*tsk+s*s)/2/t_r/t_r).*...
             (erf((t-theta-tsk-s*s/t_r)/(s*sqrt(2)))+erf((tsk+s*s/t_r)/s/sqrt(2))))-...
          (t_d/(t_d-t_r)*exp((-2*t*t_d+2*t_d*theta+2*t_d*tsk+s*s)/2/t_d/t_d).*...
             (erf((t-theta-tsk-s*s/t_d)/s/sqrt(2))+erf((tsk+s*s/t_d)/s/sqrt(2)))))).^(n-1)).*...
        ( (1 - (b * norm_irf * sqrt(pi / 2) * s *... 
        (erf((t-tsk-cer_mean)/(s*sqrt(2))) + erf((tsk+cer_mean)/(s*sqrt(2)))) + ...
          a*norm_irf*s*sqrt(pi/2)*...
         ((erf((t-theta-tsk)/s/sqrt(2))+erf(tsk/s/sqrt(2)))+...
          (t_r/(t_d-t_r)*exp((-2*t*t_r+2*t_r*theta+2*t_r*tsk+s*s)/2/t_r/t_r).*...
             (erf((t-theta-tsk-s*s/t_r)/(s*sqrt(2)))+erf((tsk+s*s/t_r)/s/sqrt(2))))-...
          (t_d/(t_d-t_r)*exp((-2*t*t_d+2*t_d*theta+2*t_d*tsk+s*s)/2/t_d/t_d).*...
             (erf((t-theta-tsk-s*s/t_d)/s/sqrt(2))+erf((tsk+s*s/t_d)/s/sqrt(2))))))).^(N-n)).*...
	( (1.0/(sqrt(l*l+s*s)))*sqrt(pi/2)*l*s*norm_c*b*norm_irf*...
        (exp(-(tsk+cer_mean-t).*(tsk+cer_mean-t)/2/(l*l+s*s)).*...
	  ( erf((-tsk*l*l+cer_mean*s*s+l*l*(t-cer_min)-s*s*t+s*s*(t-cer_min))/(sqrt(2)*l*s*sqrt(l*l+s*s)))-...
            erf((-tsk*l*l+cer_mean*s*s-s*s*t)/(sqrt(2)*l*s*sqrt(l*l+s*s)))))+...
	sqrt(pi/2)*s*norm_irf*norm_s*a*...
          (exp((s*s-2*t*t_d+2*t_d*tsk+2*t_d*theta)/(2*t_d*t_d)).*...
	    (erf((t_d*(t-theta-tsk)-s*s)/(sqrt(2)*s*t_d))+erf((t_d*tsk +s*s)/(sqrt(2)*s*t_d)))+...
           exp((s*s-2*t*t_r+2*t_r*tsk+2*t_r*theta)/(2*t_r*t_r)).*...
            (erf((t_r*(t-theta-tsk)-s*s)/(sqrt(2)*s*t_r))+erf((t_r*tsk +s*s)/(sqrt(2)*s*t_r)))));

%CFS=@(t) sum(nchoosek(N, (n:N))*(CF^(n:N))*((1-CF)^(N-(n:N))));

x=0*s:binning:100e-9;

figure;
hold on;
plot(x,CFS(x)); 
